           <a href="http://www.sonnenkinderverein.de/index.htm">SONNENKINDER</a> ||
	  <a href="http://www.sonnenkinderverein.de/projekte/projekte.htm">PROJEKTE</a> ||
	  <a href="http://www.sonnenkinderverein.de/usu/usu.htm">HELFEN SIE HELFEN!</a> ||
	  <a href="http://www.sonnenkinderverein.de/helfer/helfer.htm">UNSERE HELFER</a> ||
	  <a href="http://www.sonnenkinderverein.de/kontakt/kontakt.htm">KONTAKT</a>